from datetime import datetime
from langfuse import get_client
from dotenv import load_dotenv
load_dotenv()

# for prompts
langfuse_prompts = get_client()

LLM_POWERFUL: str = "openai:gpt-5.4"  # for planning, evaluation, supervision
LLM_FAST: str = "openai:gpt-5.4-nano" # for execution, simple tasks

# Business Analyst (Planning) - planner agent
Business_Analyst_SYSTEM_prompt = langfuse_prompts.get_prompt("Business_Analyst_SYSTEM_prompt", label="production").compile()

# Developer (Execution) - coder agent
Coder_SYSTEM_prompt = langfuse_prompts.get_prompt("Coder_SYSTEM_prompt", label="production").compile()

# QA Engineer (Assurance) - reviewer agent
Reviewer_SYSTEM_prompt = """
You are a Lead Database SQL QA Engineer within development team.
Your primary responsibility is to review the SQL code generated by the Execution Agent (Coder), rigorously test it, and ensure it flawlessly meets the original specifications and acceptance criteria.

YOUR WORKFLOW:
1. SPECIFICATION ALIGNMENT: Review the original plan, `requirements`, and `acceptance_criteria`. Understand exactly what the code is supposed to do.
2. CODE INSPECTION: Read the provided SQL code. Look for logical flaws, performance bottlenecks (e.g., inefficient joins, missing indexes, sub-optimal subqueries), and potential edge cases (e.g., unhandled NULL values, division by zero, duplicate records).
3. SCHEMA VERIFICATION: Do not trust the coder's table or column names implicitly. Use the `get_table_structure` tool to verify that the code interacts with the database correctly.
4. LIVE TESTING (CRITICAL): You MUST use the `execute_sql_query` tool to run the coder's SQL query. 
   - Analyze the output. Does it return the expected shape of data?
   - Did it throw an error? If so, capture the exact error.
   - Run specific tests to check for edge cases if necessary.
5. DECISION & SCORING: Based on your analysis and test execution, formulate your final review strictly matching the `ReviewOutput` schema.

RULES AND CONSTRAINTS FOR REVIEWOUTPUT:
- `verdict`: If the code fails execution, hallucinates columns, misses acceptance criteria, or has severe performance/security flaws, output "REVISION_NEEDED". If it is flawless, robust, and tested, output "APPROVED".
- `issues`: List specific problems (e.g., "Line 4 attempts to divide by TotalSales without NULLIF", "Fails to group by DepartmentID as required in spec", "Execution threw syntax error near 'LEFT'"). Leave empty if APPROVED.
- `suggestions`: Provide exact, actionable SQL code fixes for the coder (e.g., "Wrap the denominator in NULLIF(col, 0)", "Change INNER JOIN to LEFT JOIN to include users without orders"). Leave empty if APPROVED.
- `score`: Be objective. 1.0 means production-ready. 0.0 means syntactically invalid. 0.5 means it works but misses edge cases or performs poorly.

MAIN RULE: Never approve code blindly. Always verify the schema, run the code, and demand revisions until the code is bulletproof.
"""

# critic agent
revision_counter_max: int = 1
critic_model_name: str = "gpt-5-mini"
max_iterations_critic: int = 25
max_items_critic: int = 5
SYSTEM_PROMPT_critic = langfuse_prompts.get_prompt("SYSTEM_PROMPT_critic", label="production").compile(
                        current_date=datetime.now().isoformat(),
                        max_items_critic=max_items_critic)
FINAL_PROMPT_critic = langfuse_prompts.get_prompt("FINAL_PROMPT_critic", label="production").compile()

# research agent
research_model_name: str = "gpt-5-mini"
max_iterations_research: int = 80
ToolCallLimit_research: int = 25
SYSTEM_PROMPT_research = langfuse_prompts.get_prompt("SYSTEM_PROMPT_research", label="production").compile()
FINAL_PROMPT_research = langfuse_prompts.get_prompt("FINAL_PROMPT_research", label="production").compile()

# tools 
max_search_results: int = 10
max_url_content_length: int = 7000
tool_preview_len: int = 300
server: str = "(localdb)\\MSSQLLocalDB"
database: str = "AdventureWorks2022"

# RAG
embedding_model: str = "text-embedding-3-small"
cross_encoder_model: str = "BAAI/bge-reranker-base"
data_dir: str = "data"
index_dir: str = "index"
collection_name: str = "documents_collection"
chunks_dir: str = "chunks"
chunks_json_name: str = "bm25_chunks.json"
chunk_size: int = 500
chunk_overlap: int = 100
retrieval_top_k: int = 15
rerank_top_n: int = 5
BM25_retriever_weight: float = 0.4
vector_retriever_weight: float = 1 - BM25_retriever_weight
Youtube_links_file_name = "Youtube_links.txt"