table 'Business Area'
	lineageTag: 20554ca2-da22-41ec-8bd9-5f37ab96c7a0

	column 'Business Area'
		dataType: string
		lineageTag: 4591f1ec-7dfc-4837-95f4-525fc7452ae7
		summarizeBy: none
		sourceColumn: Business Area

		annotation SummarizationSetBy = Automatic

	column 'Business Area ID'
		dataType: double
		isHidden
		lineageTag: 2fe3a0fc-5beb-44b9-8589-0bef1e342b4f
		summarizeBy: none
		sourceColumn: Business Area ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Business Area' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mad\Dropbox\Work\Obvience\IP\IT\Data\Clean\Data.xlsx"), null, true),
				    Sheet = Source{[Item="Business Area",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers", {{"Business Area", "Business Area"}, {"Business Area ID", "Business Area ID"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Business Area", type text}, {"Business Area ID", type number}})
				 in
				    #"Changed Type"

