from langchain_core.tools import tool
from agents.planner import planner_agent
from agents.critic import critic_agent
from agents.research import research_agent
from config import SUPERVISOR_PROMPT, supervisor_model_name
from langchain.agents import create_agent
from tools import write_report
from langchain.agents.middleware import HumanInTheLoopMiddleware
from langgraph.checkpoint.memory import InMemorySaver

@tool
def research_planner(request: str) -> str:
    """Create structured, step-by-step research plans from user requests.

    Usage:
    - Break down a question or topic into an actionable research strategy
    - Formulate specific search queries and determine the best data sources (web vs. internal)
    - Define the optimal structure and formatting for a final research report

    Input: Natural language research topic or request
    (e.g., 'Create a plan to research the market impact of solid-state batteries')
    """
    result = planner_agent.invoke(
        {"messages": [{"role": "user", "content": request}]}
    )
    plan = result.get("structured_response")
    return plan.model_dump_json(indent=2) if plan else str(result)

@tool
def reseacrh_execution(request: str) -> str:
    """Execute deep-dive research and generate a comprehensive Markdown report.

    Usage:
    - Execute a structured research plan or answer a complex, multi-step query
    - Gather detailed facts, statistics, and deep context from full articles (not just search snippets)
    - Search across external web sources, internal databases, financial data, or academic articles
    - Find current information from the web
    - Look up company policies, contacts, or OKRs
    - Get summaries of internal documentation
    - Compile gathered findings into a final, well-formatted Markdown report

    Input: A specific research query or a detailed research plan generated by the Planner.
    (e.g., 'Execute this research plan: Goal is to analyze TSLA financials. Queries: ...')
    """
    result = research_agent.invoke(
        {"messages": [{"role": "user", "content": request}]}
    )
    research = result.get("structured_response")
    return research.model_dump_json(indent=2) if research else str(result)

@tool
def research_critic(request: str) -> str:
    """Independently review, fact-check, and evaluate a drafted research report.

    Usage:
    - Verify if the findings in a drafted report are accurate, up-to-date, and supported by sources
    - Check if the research fully covers the user's original request (completeness)
    - Assess the logical structure of the drafted text
    - Get a final verdict (APPROVE or REVISE) along with specific actionable revision requests

    Input: A string containing BOTH the original user request and the drafted research report.
    (e.g., 'Original request: [Topic]. Draft report: [Markdown text...]')
    """
    result = critic_agent.invoke(
        {"messages": [{"role": "user", "content": request}]}
    )
    critique = result.get("structured_response")
    return critique.model_dump_json(indent=2) if critique else str(result)

supervisor = create_agent(
    model=supervisor_model_name,
    tools=[research_planner, reseacrh_execution, research_critic, write_report],
    system_prompt=SUPERVISOR_PROMPT
)

print("\n✅ Supervisor Agent finished executing")
print("\n🏗️ System architecture:")
print("  Supervisor")
print("  ├── research_planner   → Planner Agent")
print("  ├── reseacrh_execution → Research Agent")
print("  ├── research_critic    → Critic Agent")
print("  └── write_report       → File System")

# Test 1: Simple single-domain request
for step in supervisor.stream(
    {"messages": [{"role": "user", "content": "What is PBIR?"}]}
):
    for update in step.values():
        for message in update.get("messages", []):
            message.pretty_print()