from langchain_core.tools import tool
from agents.planner import planner_agent
from agents.critic import critic_agent
from agents.research import research_agent
from config import (
    SUPERVISOR_PROMPT, 
    supervisor_model_name, 
    FINAL_PROMPT_research,
    max_iterations_research,
    max_iterations_supervisor,
    revision_counter_max
)
from langchain.agents import create_agent
from tools import save_report
from langgraph.errors import GraphRecursionError
from langchain.agents.middleware import HumanInTheLoopMiddleware
from langgraph.checkpoint.memory import InMemorySaver

revision_counter = 0

# додати HITL
# додати [Supervisor → Critic]
# переписати промт для критика, щось він занадто критичний вийшов
# подумати над лімітом ітерацій для критика, там зараз виходить 3 замість 2
# читабельний виклика тулів та їх результату (в принципі це в мене вже є, але просто загорнути в функцію) - може краще на рівні main

# дописати
def run_agent_with_recovery(agent, request: str, thread_id: str, limit: int, final_prompt: str):
    config = {"recursion_limit": limit, "configurable": {"thread_id": thread_id}}
    pass

@tool
def research_planner(request: str) -> str:
    """Create structured, step-by-step research plans from user requests.

    Usage:
    - Break down a question or topic into an actionable research strategy
    - Formulate specific search queries and determine the best data sources (web vs. internal)
    - Define the optimal structure and formatting for a final research report

    Input: Natural language research topic or request
    (e.g., 'Create a plan to research the market impact of solid-state batteries')
    """
    result = planner_agent.invoke(
        {"messages": [{"role": "user", "content": request}]}
    )
    plan = result.get("structured_response")
    return plan.model_dump_json(indent=2) if plan else str(result)

@tool
def reseacrh_execution(request: str) -> str:
    """Execute deep-dive research and generate a comprehensive Markdown report.

    Usage:
    - Execute a structured research plan or answer a complex, multi-step query
    - Gather detailed facts, statistics, and deep context from full articles (not just search snippets)
    - Search across external web sources, internal databases, financial data, or academic articles
    - Find current information from the web
    - Look up company policies, contacts, or OKRs
    - Get summaries of internal documentation
    - Compile gathered findings into a final, well-formatted Markdown report

    Input: A specific research query or a detailed research plan generated by the Planner.
    (e.g., 'Execute this research plan: Goal is to analyze TSLA financials. Queries: ...')
    """
    config = {
        "recursion_limit": max_iterations_research, 
        "configurable": {"thread_id": "research_thread"}
    }
    
    try:
        result = research_agent.invoke(
            {"messages": [{"role": "user", "content": request}]},
            config=config
        )
        res = result.get("structured_response")
        return res.research_output if res else str(result)
        
    except GraphRecursionError as e:
        print("\n⚠️ Agent stopped: Reached the maximum limit of iterations. Generating final report from gathered data...")
        # Trigger a final "Report" prompt
        current_state = research_agent.get_state(config)
        messages = current_state.values.get("messages", [])
        recovery_messages = []
        
        if messages and hasattr(messages[-1], "tool_calls") and messages[-1].tool_calls:
            for tc in messages[-1].tool_calls:
                recovery_messages.append({
                    "role": "tool",
                    "tool_call_id": tc["id"],
                    "name": tc["name"],
                    "content": "System Abort: Tool execution cancelled because iteration limit was reached."
                })
        recovery_messages.append({"role": "user", "content": FINAL_PROMPT_research})
       
        try:
            final_result = research_agent.invoke(
                {"messages": recovery_messages},
                config=config
            )
            res = final_result.get("structured_response")
            return res.research_output if res else str(final_result)

        except Exception as inner_e:
            return f"Research Agent failed critically during recovery: {inner_e}"
    except Exception as e:
        return f"Research Agent encountered an unexpected error: {e}"

@tool
def research_critic(request: str) -> str:
    """Independently review, fact-check, and evaluate a drafted research report.

    Usage:
    - Verify if the findings in a drafted report are accurate, up-to-date, and supported by sources
    - Check if the research fully covers the user's original request (completeness)
    - Assess the logical structure of the drafted text
    - Get a final verdict (APPROVE or REVISE) along with specific actionable revision requests

    Input: A string containing BOTH the original user request and the drafted research report.
    (e.g., 'Original request: [Topic]. Draft report: [Markdown text...]')
    """
    global revision_counter
    revision_counter += 1

    result = critic_agent.invoke(
        {"messages": [{"role": "user", "content": request}]}
    )
    critique = result.get("structured_response")

    if not critique:
        return str(result)

    if revision_counter > revision_counter_max and critique.verdict == "REVISE":
        print(f"\n⚠️ Critic Tool: Reached maximum revisions ({revision_counter}). Forcing APPROVE.")
        critique.verdict = "APPROVE"
        critique.revision_requests = ["Achieved max number of iterations. Report is approved, it is the final version, save it."]

    return f"--- CRITIQUE ROUND {revision_counter}/2 ---\n" + critique.model_dump_json(indent=2)

config = {
    "configurable": {"thread_id": "supervisor_thread"}, 
    "recursion_limit": max_iterations_supervisor}

supervisor = create_agent(
    model=supervisor_model_name,
    tools=[research_planner, reseacrh_execution, research_critic, save_report],
    system_prompt=SUPERVISOR_PROMPT,
    checkpointer=InMemorySaver()
)

print("\n✅ Supervisor Agent finished executing")
print("\n🏗️ System architecture:")
print("  Supervisor")
print("  ├── research_planner   → Planner Agent")
print("  ├── reseacrh_execution → Research Agent")
print("  ├── research_critic    → Critic Agent")
print("  └── write_report       → File System")

# Test 1: Simple single-domain request
for step in supervisor.stream(
    {"messages": [{"role": "user", "content": "dividend policy types"}]},
    config=config
):
    for update in step.values():
        for message in update.get("messages", []):
            message.pretty_print()