table Date
	lineageTag: 24b0a89e-1f27-4430-b626-7bdac85b1cea
	dataCategory: Time

	measure 'Count of Date' = COUNTA('Date'[Date])
		lineageTag: 2b982911-97d8-4828-b00c-9a75fd54f0dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: 427aab62-f2b3-402f-8993-5cc76bca49b2
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 0f809af4-d31b-4977-a214-8f13fa42f41d
			defaultHierarchy: LocalDateTable_6f19fed3-1fc0-4f7a-878d-34aca93d6782.'Date Hierarchy'

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: d43e6b59-eddd-4f7b-9507-30a28ed5d9b2
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: MonthNumber

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column MonthNumber
		dataType: int64
		lineageTag: 494d3fd2-6dea-4cea-9f5a-07b2b5157d5d
		summarizeBy: sum
		sourceColumn: MonthNumber

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Period
		dataType: string
		lineageTag: 7565e3eb-5182-4971-ae0d-4534a4cc46f4
		summarizeBy: none
		sourceColumn: Period
		sortByColumn: PeriodNumber

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column PeriodNumber
		dataType: int64
		lineageTag: 036afe44-8234-4f3c-8129-36d8725cc308
		summarizeBy: sum
		sourceColumn: PeriodNumber

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Qtr
		dataType: int64
		lineageTag: ac1211fa-8c7c-44b8-bbf0-ce3bcc719646
		summarizeBy: sum
		sourceColumn: Qtr

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QtrNumber
		dataType: string
		lineageTag: 79801ddb-3acf-4ba4-8d0e-fe2212123d4e
		summarizeBy: none
		sourceColumn: QtrNumber

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Year
		dataType: int64
		lineageTag: 6bc013b5-c4a7-4105-bc25-8a7344fc447b
		summarizeBy: sum
		sourceColumn: Year

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Day
		dataType: int64
		lineageTag: 9d34b1fd-ce7f-42ff-a9d1-a2177c98dae4
		summarizeBy: sum
		sourceColumn: Day

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthStartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: e62147fb-3516-496e-9a09-1aada362993c
		summarizeBy: none
		sourceColumn: MonthStartDate

		variation Variation
			isDefault
			relationship: f496f9ad-5665-4785-a30e-b1bbcf7be215
			defaultHierarchy: LocalDateTable_d2ea5b26-668d-4c17-b228-695669b066a6.'Date Hierarchy'

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation SummarizationSetBy = Automatic

	column MonthEndDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 2c3d24c7-5063-4e82-ac68-79cfe4994a7c
		summarizeBy: none
		sourceColumn: MonthEndDate

		variation Variation
			isDefault
			relationship: b2a9d346-0212-432d-a1a9-57680b4a73ea
			defaultHierarchy: LocalDateTable_c9dde99e-7ac1-4e8e-a5f2-c5ffc41d9cac.'Date Hierarchy'

		annotation DataTypeAtRefresh = DateTime#####not a type

		annotation SummarizationSetBy = Automatic

	column MonthIncrementNumber = ([Year]-MIN([Year]))*12 +[MonthNumber]
		isHidden
		lineageTag: 03aa7749-d1d1-4c7e-a749-375a9ac3f352
		summarizeBy: sum

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	hierarchy YQM
		lineageTag: ce422717-7fe1-4c3e-a4e8-26337f0b334a

		level Year
			lineageTag: e7d83749-a496-4dcc-b4a5-c9bc3328441b
			column: Year

		level QtrNumber
			lineageTag: 78c4ac82-b9a4-451e-9d70-2340a35b9a0b
			column: QtrNumber

		level PeriodNumber
			lineageTag: a5fcee5e-8092-4f99-ac8b-f3a1a0e9128e
			column: PeriodNumber

	partition Date = m
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT [HR].[Date].*   FROM [HR].[Date]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Date", "Date"}, {"Month", "Month"}, {"MonthNumber", "MonthNumber"}, {"Period", "Period"}, {"PeriodNumber", "PeriodNumber"}, {"Qtr", "Qtr"}, {"QtrNumber", "QtrNumber"}, {"Year", "Year"}, {"Day", "Day"}, {"MonthStartDate", "MonthStartDate"}, {"MonthEndDate", "MonthEndDate"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Date", type datetime}, {"Month", type text}, {"MonthNumber", Int64.Type}, {"Period", type text}, {"PeriodNumber", Int64.Type}, {"Qtr", Int64.Type}, {"QtrNumber", type text}, {"Year", Int64.Type}, {"Day", Int64.Type}, {"MonthStartDate", type datetime}, {"MonthEndDate", type datetime}})
				in
				    #"Changed Type"

	annotation __PBI_LegacyCustomDateTable = true

