table Gender
	lineageTag: 5051d289-0e22-4dd7-9b14-e6b80ca94136

	column ID
		dataType: string
		isHidden
		lineageTag: 2e29fc62-39dd-4b93-9800-7287d3b9fc95
		summarizeBy: none
		sourceColumn: ID

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Gender
		dataType: string
		lineageTag: 12bf4dd0-eb78-4df3-9ae2-79ed9e09741a
		summarizeBy: none
		sourceColumn: Gender
		sortByColumn: Sort

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Sort
		dataType: int64
		isHidden
		lineageTag: ea4445f6-4352-4d03-93ad-3900f7b16346
		summarizeBy: none
		sourceColumn: Sort

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Gender = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WclHSUfJNzEkFUoZKsTrRSs5AlltqLkTISCk2FgA=", BinaryEncoding.Base64), Compression.Deflate))),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Column1", "ID"}, {"Column2", "Gender"}, {"Column3", "Sort"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"ID", type text}, {"Gender", type text}, {"Sort", Int64.Type}})
				 in
				    #"Changed Type"

