table SeparationReason
	lineageTag: 42c2b9dd-c8c7-4c61-b1b8-12970743f969

	column SeparationTypeID
		dataType: string
		isHidden
		lineageTag: 17a7b2c9-d436-4c95-ab95-1d091a0df867
		summarizeBy: none
		sourceColumn: SeparationTypeID

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

	column SeparationReason
		dataType: string
		lineageTag: d34deaa4-09ac-4467-8765-790d209b6883
		summarizeBy: none
		sourceColumn: SeparationReason

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

	partition TermReason = m
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT distinct SeparationTypeID, [Vol-Invol] SeparationReason#(lf)  FROM [IP].[HR].[TermReason]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"SeparationTypeID", "SeparationTypeID"}, {"SeparationReason", "SeparationReason"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"SeparationTypeID", type text}, {"SeparationReason", type text}})
				in
				    #"Changed Type"

