table BU
	lineageTag: 1a409ea1-d472-493e-8220-d843f22d87a0

	column 'BU Key'
		dataType: double
		isHidden
		lineageTag: 0232210e-dec0-4fd9-a8c0-fbfb8c826912
		summarizeBy: none
		sourceColumn: BU Key

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BU
		dataType: string
		lineageTag: d4515e12-e921-4256-ab91-c8e21892b8aa
		summarizeBy: none
		sourceColumn: BU

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Division
		dataType: string
		lineageTag: 17348b62-d44e-4ff5-9368-b5f32e8484ce
		summarizeBy: none
		sourceColumn: Division

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Executive_id
		dataType: int64
		isHidden
		lineageTag: d734fcca-871c-4e7c-882f-996805058ac9
		summarizeBy: none
		sourceColumn: Executive_id

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

	hierarchy BUHierarchy
		lineageTag: 530e0aef-fb1b-4ae5-a69d-a3e097362fdb

		level Division
			lineageTag: 31e5ff80-6e58-46ea-9306-88e58764c8b5
			column: Division

		level BU
			lineageTag: 624f2d5c-c39e-471a-982d-e5cc42c5d51c
			column: BU

	partition BU = m
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT #(lf)       #(lf)      [Profit Center Key] [BU Key],#(lf)   BU,#(lf)   Division, Executive_id#(lf)  FROM [MDS].[mdm].[profitcenter]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"BU Key", "BU Key"}, {"BU", "BU"}, {"Division", "Division"}, {"Executive_id", "Executive_id"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"BU Key", type number}, {"BU", type text}, {"Division", type text}, {"Executive_id", Int64.Type}})
				in
				    #"Changed Type"

