table Customer
	lineageTag: 29c8f60a-e6f9-4a20-99c8-e5aa589d0130

	column Customer
		dataType: double
		isHidden
		lineageTag: 48b0eeea-8f29-45df-b770-e64a595853ef
		summarizeBy: none
		sourceColumn: Customer

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Country/Region
		dataType: string
		lineageTag: 357058d6-bb9f-4bea-b38a-f4c24ada9c92
		summarizeBy: none
		sourceColumn: Country/Region

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Name
		dataType: string
		lineageTag: 1b64d0e6-27c2-4b0a-8967-0e212d4bec6e
		summarizeBy: none
		sourceColumn: Name

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column City
		dataType: string
		lineageTag: bd698f0c-6b2b-4626-a7f6-6ddb048e99c2
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Postal Code'
		dataType: double
		lineageTag: 03aa9206-5c18-4ba9-9eef-0eac7a5bfdb2
		dataCategory: PostalCode
		summarizeBy: count
		sourceColumn: Postal Code

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column State
		dataType: string
		lineageTag: 1c809d42-21d5-47c0-8ba4-37c504ee454f
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column 'Industry ID'
		dataType: double
		isHidden
		lineageTag: 6249671f-4e59-42d0-95d0-08294ae6f696
		summarizeBy: none
		sourceColumn: Industry ID

		annotation DataTypeAtRefresh = Double#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	hierarchy CustomerHierarchy
		lineageTag: c24308f1-9e1e-4699-8ae1-74c94da56263

		level Country
			lineageTag: 783e0b69-5249-4689-b091-5aa804719012
			column: Country/Region

		level State
			lineageTag: a83fac0a-0b6c-46ac-8020-1c5c03da49d5
			column: State

		level City
			lineageTag: 76be37ba-4479-4748-b981-49eb6227ca7b
			column: City

		level 'Postal Code'
			lineageTag: cda20df8-67ed-48a5-8153-8f30dffc33b0
			column: 'Postal Code'

		level Customer
			lineageTag: 79b1564f-ea2c-488d-988a-e27b5de03778
			column: Customer

	partition Customer = m
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mad\Dropbox\Work\Obvience\IP\Customer and Product Profitability\Data\dimCustomer.xlsx"), null, true),
				    Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers", {{"Customer", "Customer"}, {"Country", "Country/Region"}, {"Name", "Name"}, {"City", "City"}, {"Postal Code", "Postal Code"}, {"State", "State"}, {"Industry ID", "Industry ID"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Customer", type number}, {"Country/Region", type text}, {"Name", type text}, {"City", type text}, {"Postal Code", type number}, {"State", type text}, {"Industry ID", type number}})
				 in
				    #"Changed Type"

