table Industry
	lineageTag: 49c45281-e95b-4bbf-9fb0-964c2fe15441

	column ID
		dataType: int64
		isHidden
		isKey
		keepUniqueRows
		lineageTag: acafb054-8717-4768-ade9-68d1cf01a031
		summarizeBy: none
		sourceColumn: ID

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Industry
		dataType: string
		keepUniqueRows
		lineageTag: 69a4bcdd-4106-419a-bb7e-58edfc7c6bd3
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Industry

		annotation DataTypeAtRefresh = String#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Image
		dataType: binary
		lineageTag: 586a949a-905f-451b-b5e4-9b6b749615e8
		dataCategory: Image
		isDefaultImage
		summarizeBy: none
		sourceColumn: Image

		annotation DataTypeAtRefresh = Binary#####not a type

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Industry = m
		source =
				let
				    Source = Sql.Database(".", "IP", [Query="SELECT [dbo].[Industry].*   FROM [dbo].[Industry]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"ID", "ID"}, {"Industry", "Industry"}, {"Image", "Image"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"ID", Int64.Type}, {"Industry", type text}, {"Image", type binary}})
				in
				    #"Changed Type"

